version: "3"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: postman
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 30s
      retries: 1
  postman-service:
    build:
      context: ./postman-service
    environment:
      DB_NAME: postman
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
      AMQP_URL: 'amqp://myuser:mypassword@rabbitmq:5672'
      QUEUE: 'emailQueue'
      START_TIMEOUT: 15000
    restart: on-failure
    depends_on:
      - mysqldb
      - rabbitmq
    ports:
      - '3000:3000'
volumes: 
  db: